language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
install:
  - pip install -e . --use-mirrors
  - pip install nose coverage coveralls --use-mirrors
script:
  - coverage run `which nosetests` --nocapture
  - coverage report -m
after_success:
  - coveralls
notifications:
  email: false
  slack:
    secure: Hbtx8OQOQ4WKs/Nniql+wPOSSgE9KCLAN3OiICPbi58v1YFQK+RgC/R0ictqedg2qDKpl2nRYDO6DaXw2JE+/goNbgl79V/Tw28lU5dfNXYDFo9WaxdfLwIfoN/n1csv1D8485NDqnVv7TeJbHvGmmTdx9v0vg4fenUhqVcgqHw=
