os:
  - 'linux'
language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r ./requirements/ci.txt
  - pip install --upgrade --editable .
script:
  - py.test --doctest-modules --verbose ./il2fb/commons ./tests --cov ./il2fb/commons ./tests
after_success:
  - codecov
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
  slack:
    secure: Hbtx8OQOQ4WKs/Nniql+wPOSSgE9KCLAN3OiICPbi58v1YFQK+RgC/R0ictqedg2qDKpl2nRYDO6DaXw2JE+/goNbgl79V/Tw28lU5dfNXYDFo9WaxdfLwIfoN/n1csv1D8485NDqnVv7TeJbHvGmmTdx9v0vg4fenUhqVcgqHw=
