# https://ci.appveyor.com/project/oblalex/il2fb-commons

build: false # Not a C# project, build stuff at the test step instead.
environment:
  matrix:
    - PYTHON: "C:/Python38"
    - PYTHON: "C:/Python38-x64"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py' -FileName 'C:/get-pip.py'
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -r ./requirements/ci.txt"
  - "%PYTHON%/Scripts/pip.exe install --editable ."
test_script:
  - "%PYTHON%/Scripts/py.test --doctest-modules --verbose ./il2fb/commons ./tests --cov ./il2fb/commons ./tests"
